# Generated by Django 5.2.1 on 2025-05-12 20:05

import django.utils.timezone
from django.db import migrations, models

import uvauth.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[uvauth.models.email_do_ifce_valitation],
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='first name'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='last name'
                    ),
                ),
                (
                    'campus',
                    models.CharField(
                        choices=[
                            ('ndf', 'Não definido'),
                            ('aca', 'Acaraú'),
                            ('aco', 'Acopiara'),
                            ('ara', 'Aracati'),
                            ('bat', 'Baturité'),
                            ('boa', 'Boa Viagem'),
                            ('cam', 'Camocim'),
                            ('caj', 'Canindé'),
                            ('cau', 'Caucaia'),
                            ('ced', 'Cedro'),
                            ('cra', 'Crateús'),
                            ('cro', 'Crato'),
                            ('for', 'Fortaleza'),
                            ('gua', 'Guaramiranga'),
                            ('hor', 'Horizonte'),
                            ('igu', 'Iguatu'),
                            ('ita', 'Itapipoca'),
                            ('jag', 'Jaguaribe'),
                            ('jau', 'Jaguaruana'),
                            ('juz', 'Juazeiro do Norte'),
                            ('lim', 'Limoeiro do Norte'),
                            ('mar', 'Maracanaú'),
                            ('man', 'Maranguape'),
                            ('mom', 'Mombaça'),
                            ('mor', 'Morada Nova'),
                            ('par', 'Paracuru'),
                            ('pec', 'Pecém'),
                            ('pol', 'Polo de Inovação'),
                            ('qui', 'Quixadá'),
                            ('rei', 'Reitoria'),
                            ('sob', 'Sobral'),
                            ('tab', 'Tabuleiro do Norte'),
                            ('tau', 'Tauá'),
                            ('tia', 'Tianguá'),
                            ('uba', 'Ubajara'),
                            ('umi', 'Umirim'),
                        ],
                        default='ndf',
                        max_length=3,
                    ),
                ),
                (
                    'vinculo',
                    models.CharField(
                        choices=[
                            ('doc', 'Docente'),
                            ('dis', 'Discente'),
                            ('tae', 'Técnico Administrativo'),
                            ('des', 'Desconhecido'),
                        ],
                        default='doc',
                        max_length=3,
                        verbose_name='vínculo',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name='date joined'
                    ),
                ),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.permission',
                        verbose_name='user permissions',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
